### ISSUE TITLE
/etc directory can't access in macos docker

### ISSUE THREAD

**Issue by cenzhipeng** [citahub/cita-monitor#127]
I noticed that the docker-compose uses the '/etc/localtime' and the '/etc/timezone', but this doesn't work in macos, in macos you can't use volumn on /etc directory, it will report an error. I solved this problem by modify the docker-compose and volumn an another localtime into docker.

**Comment by rainchen** [comment]
/etc/timezone issue been fixed in PR #109 , and has been merged into the develop branch, you can try using the develop branch, but it's still in the active development stage.

**Comment by rainchen** [comment]
@cenzhipeng any feedback? or I will close this issue, FYI.
