### ISSUE TITLE
control data dir size checking frequency

### ISSUE THREAD

**Issue by rainchen** [citahub/cita-monitor#130]
问题：使用du 命令获取目录容量会影响性能
解决：降低data dir size 检查的频度，改为1个小时检查获取一次。
做法：把 du 的结果导到一个文件，执行 du 前判断文件修改时间和当前时间对比是否达到采集区间，没达到阀值就cat 结果，这样来做采集频率控制

**Comment by jiangxianliang007** [comment]
done
