### ISSUE TITLE
quota info seems not work 

### ISSUE THREAD

**Issue by xiangmeiLu** [citahub/cita-monitor#85]
When I use this monitor, in the "Node Info Dashboard"--> "quota info" district, I didn't see the difference between the a non-zero Quota Used and the zero quota-used.  screenshot pasted here.

**Comment by xiangmeiLu** [comment]
![0](https://user-images.githubusercontent.com/30581938/57899063-17b5f280-788e-11e9-8314-9a86dc2e7d52.jpg)
![2](https://user-images.githubusercontent.com/30581938/57899065-197fb600-788e-11e9-8c3d-8f9a21e0dba6.jpg)

**Comment by blankwu** [comment]
The histogram is composed of 'block limit' and 'quota used'. Since the 'quota used' is very low compared to the 'block limit', it cannot be found in the graph.
Unless the value of 'quota used' becomes larger;
Or you can modify the parameters of grafana: Axes -> Scale -> log(base 32) or larger

**Comment by xiangmeiLu** [comment]
Got it!  Thanks!
